baseURL = 'https://prakash4844.github.io/Let-s-Learn-Linux/'
languageCode = 'en-us'
title = "Let's Learn Linux"

# Change the default theme to be use when building the site with Hugo
theme = "relearn"

# For search functionality
[outputs]
# add JSON to the home to support lunr search; This is a mandatory setting
# for the search functionality
# add PRINT to home, section and page to activate the feature to print whole
# chapters
home = [ "HTML", "RSS", "SEARCH", "SEARCHPAGE", "PRINT"]
section = ["HTML", "RSS", "PRINT"]
page = ["HTML", "RSS", "PRINT"]


[params]
author = "Prakash4844"
alwaysopen = false
# Description of the site, will be used in meta information
description = "This site is an attempt to revive the Famous Website 'LinuxJourney' and inherit the text data from it's repository."

# Shows a checkmark for visited pages on the menu
showVisitedLinks = true

# Disable search function. It will hide search bar
disableSearch = false

# Change default color scheme with a variant one. Eg. can be "red", "blue", "green" or an array like [ "blue", "green" ].
themeVariant = ["relearn-dark", "relearn-light","relearn-bright","red", "blue", "green","neon", "learn"]

# Change the title separator. Default to "::".
titleSeparator = "::"

# If set to true, the menu in the sidebar will be displayed in a collapsible tree view. Although the functionality works with old browsers (IE11), the display of the expander icons is limited to modern browsers
collapsibleMenu = true

# canonicalization will only be used for the sitemap.xml and index.xml files;
# if set to false, a site served from a subdirectory will generate wrong links
# inside of the above mentioned files; if you serve the page from the servers root
# you are free to set the value to false as recommended by the official Hugo documentation
canonifyURLs = true # true -> all relative URLs would instead be canonicalized using baseURL

# required value to serve this page from a webserver AND the file system;
# if you don't want to serve your page from the file system, you can also set this value
# to false
relativeURLs = true # true -> rewrite all relative URLs to be relative to the current content

# if you set uglyURLs to false, this theme will append 'index.html' to any branch bundle link
# so your page can be also served from the file system; if you don't want that,
# set disableExplicitIndexURLs=true in the [params] section

uglyURLs = false     # true -> basic/index.html -> basic.html

# We disable this for testing the exampleSite; you must do so too
# if you want to use the themes parameter disableGeneratorVersion=true;
# otherwise Hugo will create a generator tag on your home page
disableHugoGeneratorInject = true

disableSeoHiddenPages = true
ordersectionsby = "weight"

# English is the default language
defaultContentLanguage = "en"

[Languages]
  [Languages.en]
    title = "Let's Learn Linux"
    weight = 1
    languageName = "English"
    landingPageName = "<i class='fas fa-home'></i> Home"
    contentDir = "content/english"


  [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
    identifier = "ds"
    url = "https://github.com/Prakash4844/Let-s-Learn-Linux"
    weight = 10

  # [[Languages.en.menu.shortcuts]]
  #   name = "<i class='fab fa-fw fa-github'></i> Relearn Docs"
  #   url = "https://mcshelby.github.io/hugo-theme-relearn/index.html"
  #   weight = 11

  # [[Languages.en.menu.shortcuts]]
  #   name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
  #   identifier = "hugodoc"
  #   url = "https://gohugo.io/documentation/"
  #   weight = 20

  [Languages.hi]
    title = "आइए जानें लिनक्स"
    languageName = "हिंदी"
    landingPageName = "<i class='fas fa-home'></i> Home"
    contentDir = "content/hindi"
  
    [[Languages.hi.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
    identifier = "ds"
    url = "https://github.com/Prakash4844/Let-s-Learn-Linux"
    weight = 10

  # [[Languages.hi.menu.shortcuts]]
  #   name = "<i class='fab fa-fw fa-github'></i> Relearn Docs"
  #   url = "https://mcshelby.github.io/hugo-theme-relearn/index.html"
  #   weight = 11

  # [[Languages.hi.menu.shortcuts]]
  #   name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
  #   identifier = "hugodoc"
  #   url = "https://gohugo.io/documentation/"
  #   weight = 20