name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello! Welcome to Let's Learn Linux issue section. Thanks for taking the time to create the issue. we will check it out soon."
        pr-message: "Hello! Welcome to Let's Learn Linux PR section. Thanks for Creating a pull request, we will check it out soon."
